ingreso:
  pattern: /ingreso
  defaults: {_controller: AEloginBundle:Default:login }
  
ingreso_check:
  pattern: /ingreso_check

salir:
  pattern: /salir
  
main:
  pattern: /main
  defaults: {_controller: AEloginBundle:Default:main}
  
sobre:
  pattern: /sobre
  defaults: {_controller: AEloginBundle:Default:sobre}
  
contacto:
  pattern: /contacto
  defaults: {_controller: AEloginBundle:Default:contacto}
  
contacto_up:
  pattern: /contacto_up
  defaults: {_controller: AEloginBundle:Default:contactoUp}
  requirements:
    _method: POST