parameters:
#    a_elogin.example.class: AE\loginBundle\Example

services:
#    a_elogin.example:
#        class: %a_elogin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
