
#consolidadores activos y no activos
servicio_consolidadores:
  pattern: /lconsolidadores
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lconsolidadores}
  
#leche espirituales
servicio_leche_espiritual:
  pattern: /leche_espiritual
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lista_espiritual}
  requirements:
    _method: POST
    
#consolidadores activos
servicio_consolidadores_act:
  pattern: /l_act_consolidadores
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:l_act_consolidadores}
  requirements:
   _method: POST
    
#leche espiritual temas

servicio_leche_esp_temas:
  pattern: /leche_esp_temas/{id}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:leche_esp_temas}
  requirements:
    _method: POST
    
servicio_nuevos_consolidadores:
  pattern: /nuevos_consolidadores
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:nuevos_consolidadores}
  
servicio_consolidado_termino:
  pattern: /consolidado_termino
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado_termino}
  
servicio_consolidado_seguir:
  pattern: /consolidado_seguir
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado_seguir}
  
servicio_consolidado:
  pattern: /consolidado/{id}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado}
  requirements:
    _method: POST
    
    
servicio_temas_id:
  pattern: /temas/{cons}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:temas}
  requirements:
    _method: POST
    
    
servicio_por_descartar:
  pattern: /pordescartar
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:pordescartar}
  
servicio_lista_descartados:
  pattern: /lista_descartados
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lista_descartados}
  
  
servicio_consolidador_consolidado:
  pattern: /consolidador_consolidado
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidador_consolidado}
  
servicio_getHerramientas:
  pattern: /get_tools
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getTools}
  
  
servicio_no_consolidados:
  pattern: /get_no_consolidados/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getNoConsolidados}
  
servicio_herramienta_nuevos:
  pattern: /get_herramienta_nuevos/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getHerramientaNuevos}
  requirements:
    _method: POST