
#consolidadores activos y no activos
servicio_consolidadores:
  pattern: /lconsolidadores
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lconsolidadores}
  
servicio_consolidadores_red:
  pattern: /lconsolidadores_red/{red}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lconsolidadores_red}
  
#leche espirituales
servicio_leche_espiritual:
  pattern: /leche_espiritual
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lista_espiritual}
  requirements:
    _method: POST
    
#consolidadores activos
servicio_consolidadores_act:
  pattern: /l_act_consolidadores
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:l_act_consolidadores}
  requirements:
   _method: POST
   
   
#consolidadores activos por red
servicio_consolidadores_act_red:
  pattern: /l_act_consolidadores_red/{id}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:l_act_consolidadores_red}
  requirements:
   _method: POST
    
#leche espiritual temas

servicio_leche_esp_temas:
  pattern: /leche_esp_temas/{id}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:leche_esp_temas}
  requirements:
    _method: POST
    
servicio_nuevos_consolidadores:
  pattern: /nuevos_consolidadores
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:nuevos_consolidadores}
  
servicio_nuevos_consolidadores_red:
  pattern: /nuevos_consolidadores_red/{red}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:nuevos_consolidadores_red}
  
servicio_consolidado_termino:
  pattern: /consolidado_termino
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado_termino}
  
servicio_consolidado_termino_red_year:
  pattern: /consolidado_termino_red/{red}/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado_termino_red_year}
  
servicio_consolidado_termino_red_year_cons:
  pattern: /consolidado_termino_red/{red}/{inicio}/{fin}/{cons}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado_termino_red_year_cons}
  
servicio_consolidado_seguir:
  pattern: /consolidado_seguir
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado_seguir}
  
servicio_consolidado_seguir_red_consol:
  pattern: /consolidado_seguir_red/{red}/{consol}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado_seguir_red}
  
servicio_consolidado:
  pattern: /consolidado/{id}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidado}
  requirements:
    _method: POST
    
    
servicio_temas_id:
  pattern: /temas/{cons}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:temas}
  requirements:
    _method: POST
    
    
servicio_por_descartar:
  pattern: /pordescartar
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:pordescartar}
  
servicio_por_descartar_red:
  pattern: /pordescartar_red/{red}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:pordescartar_red}
  
servicio_lista_descartados:
  pattern: /lista_descartados
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lista_descartados}
  
servicio_lista_descartados_red:
  pattern: /lista_descartados_red/{red}/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:lista_descartados_red}
  
  
servicio_consolidador_consolidado:
  pattern: /consolidador_consolidado
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidador_consolidado}
  
servicio_consolidador_consolidado_red:
  pattern: /consolidador_consolidado_red/{red}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:consolidador_consolidado_red}
  
servicio_getHerramientas:
  pattern: /get_tools
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getTools}
  
  
servicio_no_consolidados:
  pattern: /get_no_consolidados/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getNoConsolidados}
  
servicio_herramienta_nuevos:
  pattern: /get_herramienta_nuevos/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getHerramientaNuevos}
  requirements:
    _method: POST
    
servicio_reporte_leche_espiritual_consolida:
  pattern: /getLecheEspiritualConsolida/{inicio}/{fin}/{leche}/{red}/{consol}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getLecheEspiritualConsolida}
  requirements:
   _method: POST
   
   
servicio_reporte_descartados:
  pattern: /getDescartados/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getDescartados}
  
  
servicio_reporte_almas_por_consolidador:
  pattern: /getReporteAlmasConsolidador/{id}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:getReporteAlmasConsolidador}
  
  
servicio_informe_consolidar_semanal_pastor:
  pattern: /servicio_informe_consolidar_semanal/{pastor}/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:ConsolidarServicio:informe_semanal_consolidar_pastor}