_lista_cursos:
  pattern: /_lista_cursos/{tipo}
  defaults: {_controller: AEServiciosBundle:DiscipularServicio:getCursosOption }
  
_tabla_miembros_no_personal:
  pattern: /_tabla_miembros_no_personal
  defaults: {_controller: AEServiciosBundle:DiscipularServicio:getTablaMiembros }
  
_tabla_personal:
  pattern: /_tabla_personal
  defaults: {_controller: AEServiciosBundle:DiscipularServicio:getTablaPersonal }