_enviar_lista_red:
  pattern: /enviar_lista_red
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaRed }
  requirements:
    _method: POST
    
    
_enviar_lista_celulas:
  pattern: /enviar_lista_celulas
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelula}
  
_enviar_lista_lider_red_cell:
  pattern: /enviar_lista_lider_red_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderRedCell}
  requirements:
    _method: POST
  
_enviar_lista_misionero_cell:
  pattern: /enviar_lista_misionero_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderMisioneroCell}
  requirements:
    _method: POST
  
_enviar_lista_pastor_ejecutivo_cell:
  pattern: /enviar_lista_pastor_eje_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderPastorEjeCell}
  requirements:
    _method: POST
    
_enviar_lista_lideres_cell:
  pattern: /enviar_lista_lideres_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderCell}
  requirements:
    _method: POST
   
_enviar_lista_celula_tabla:
  pattern: /enviar_lista_celula_tabla
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaTabla}
  
_enviar_lista_celula_tabla_red:
  pattern: /enviar_lista_celula_tabla_red/{red}/{tipo}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaTabla_red}
  
_enviar_lista_celula_lider_red:
  pattern: /enviar_lista_celula_lider_red/{red}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaLider_red}
  
_enviar_lista_celula_lider12_red:
  pattern: /enviar_lista_celula_lider12_red/{red}/{lider}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaLider12_red}
  
_enviar_lista_celula_tabla_des:
  pattern: /enviar_lista_celula_tabla_des
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaTablaDes}
  
_enviar_lista_celula_red_tipo:
  pattern: /enviar_lista_celula_red_tipo/{red}/{tipo}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaRedTipo}
  #requirements:
    #_method: POST
    
_enviar_lista_celula_temas:
   pattern: /enviar_lista_celula_temas/{id}
   defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaTemas}
   
_enviar_asistencia_celula_class:
  pattern: /enviar_asistencia_celula_class/{id}/{tipo}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getAsistenciaCelulaClass}
  
servicio_enviar_temas_celula:
  pattern: /temas_celula
  defaults: {_controller: AEServiciosBundle:EnviarServicio:temas_celula}
   
   
servicio_enviar_contar_clase_celula:
  pattern: /contar_clase_celula
  defaults: {_controller: AEServiciosBundle:EnviarServicio:contar_clase_celula}
  
  
servicio_enviar_lista_celulas:
  pattern: /serv_enviar_lista_celulas
  defaults: {_controller: AEServiciosBundle:EnviarServicio:serv_enviar_lista_celulas}
  
  
_enviar_lista_lideres_celula_tabla:
  pattern: /enviar_lideres_celula_tabla/{id}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLideresCelulaTabla}
  
servicio_enviar_celula_discipulado:
  pattern: /enviar_celula_discipulado/{red}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getCelulasDiscipulado}
  requirements:
    _method: POST
    
servicio_informacion_celula:
  pattern: /enviar_informacion_celula/{id}/{ini}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getInfoCelula}
  requirements:
    _method: POST
  
servicio_asistencia_celula:
  pattern: /enviar_asistencia_celula/{id}/{inicio}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getAsistenciaCelula}
  requirements:
    _method: POST
    
    
servicio_ofrenda_celula:
  pattern: /enviar_ofrenda_celula/{id}/{inicio}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getOfrendaCelula}
  requirements:
   _method: POST
    
servicio_informe_enviar_semanal_pastor:
  pattern: /servicio_informe_enviar_semanal/{pastor}/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:informe_semanal_enviar_pastor}
  requirements:
    _method: POST
  
servicio_informe_enviar_semanal_resumido:
  pattern: /servicio_informe_enviar_semanal_resumido/{pastor}/{pastora}/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:informe_enviar_semanal_resumido}
  requirements:
    _method: POST
    
servicio_miembros_sin_discipulado:
  pattern: /serviciomiembro_sin_discipulado/{red}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:miembrosindiscipulado}
  
servicio_miembros_con_discipulado:
  pattern: /serviciomiembro_con_discipulado/{red}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:miembrocondiscipulado}
  
servicio_celulas_discipulado_red:
  pattern: /celulas_discipulado/{red}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:celulas_discipulado}
  requirements:
    _method: POST
    
    
servicio_info_celula_red:
  pattern: /info_celula_red/{red}/{tipo}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:info_celula_red}
  requirements:
    _method: POST
  
servicio_info_celula_red_lider:
  pattern: /info_celula_red_lider/{red}/{lider}/{tipo}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:info_celula_red_lider}
  requirements:
    _method: POST