_enviar_lista_red:
  pattern: /enviar_lista_red
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaRed }
  requirements:
    _method: POST
    
    
_enviar_lista_celulas:
  pattern: /enviar_lista_celulas
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelula}
  
_enviar_lista_lider_red_cell:
  pattern: /enviar_lista_lider_red_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderRedCell}
  requirements:
    _method: POST
  
_enviar_lista_misionero_cell:
  pattern: /enviar_lista_misionero_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderMisioneroCell}
  requirements:
    _method: POST
  
_enviar_lista_pastor_ejecutivo_cell:
  pattern: /enviar_lista_pastor_eje_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderPastorEjeCell}
  requirements:
    _method: POST
    
_enviar_lista_lideres_cell:
  pattern: /enviar_lista_lideres_cell
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLiderCell}
  requirements:
    _method: POST
   
_enviar_lista_celula_tabla:
  pattern: /enviar_lista_celula_tabla
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaTabla}
  
  
_enviar_lista_celula_tabla_des:
  pattern: /enviar_lista_celula_tabla_des
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaTablaDes}
  
_enviar_lista_celula_red_tipo:
  pattern: /enviar_lista_celula_red_tipo/{red}/{tipo}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaRedTipo}
  #requirements:
    #_method: POST
    
_enviar_lista_celula_temas:
   pattern: /enviar_lista_celula_temas/{id}
   defaults: {_controller: AEServiciosBundle:EnviarServicio:getListaCelulaTemas}
   
_enviar_asistencia_celula_class:
  pattern: /enviar_asistencia_celula_class/{id}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getAsistenciaCelulaClass}
  
servicio_enviar_temas_celula:
  pattern: /temas_celula
  defaults: {_controller: AEServiciosBundle:EnviarServicio:temas_celula}
   
   
servicio_enviar_contar_clase_celula:
  pattern: /contar_clase_celula
  defaults: {_controller: AEServiciosBundle:EnviarServicio:contar_clase_celula}
  
  
servicio_enviar_lista_celulas:
  pattern: /serv_enviar_lista_celulas
  defaults: {_controller: AEServiciosBundle:EnviarServicio:serv_enviar_lista_celulas}
  
  
_enviar_lista_lideres_celula_tabla:
  pattern: /enviar_lideres_celula_tabla/{id}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getLideresCelulaTabla}
  
servicio_enviar_celula_discipulado:
  pattern: /enviar_celula_discipulado/{red}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getCelulasDiscipulado}
  requirements:
    _method: POST
    
servicio_informacion_celula:
  pattern: /enviar_informacion_celula/{id}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getInfoCelula}
  
servicio_asistencia_celula:
  pattern: /enviar_asistencia_celula/{id}/{inicio}/{fin}
  defaults: {_controller: AEServiciosBundle:EnviarServicio:getAsistenciaCelula}