servicio_red:
  pattern: /serviciored
  defaults: {_controller: AEServiciosBundle:GanarServicio:red}
  requirements:
    _method: POST  
    
servicio_region:
  pattern: /servicioregion
  defaults: {_controller: AEServiciosBundle:GanarServicio:region}
  requirements:
    _method: POST
    
  
servicio_provincia:
  pattern: /servicioprovincia/{id}
  defaults: {_controller: AEServiciosBundle:GanarServicio:provincia}
  requirements:
    _method: POST
  
servicio_distrito:
  pattern: /serviciodistrito/{dep}/{prov}
  defaults: {_controller: AEServiciosBundle:GanarServicio:distrito}
  requirements:
    _method: POST
    
servicio_lugar:
  pattern: /serviciolugar
  defaults: {_controller: AEServiciosBundle:GanarServicio:lugar}
  
servicio_celula:
  pattern: /serviciocelula/{id}
  defaults: {_controller: AEServiciosBundle:GanarServicio:celula}
  requirements:
    _method: POST
    
servicio_nuevo_convertido_all:
  pattern: /lista_convertidos
  defaults: {_controller: AEServiciosBundle:GanarServicio:listaconvertidos}
  
servicio_persona_id:
  pattern: /persona/{id}
  defaults: {_controller: AEServiciosBundle:GanarServicio:persona}
  requirements:
   _method: POST
   
   
servicio_ubigeo:
  pattern: /servicioubigeo/{id}
  defaults: {_controller: AEServiciosBundle:GanarServicio:ubigeo}
  
servicio_nuevo_convertido_id:
  pattern: /nuevoconvertido/{id}
  defaults: {_controller: AEServiciosBundle:GanarServicio:nuevoconvertido}
  requirements:
    _method: POST
    
servicio_lugar_id:
  pattern: /serviciolugarid/{id}
  defaults: {_controller: AEServiciosBundle:Default:lugarid}
  
servicio_tabla_ganar_fecha:
  pattern: /servicio_tabla_ganar_fecha/{fecha1}/{fecha2}
  defaults: {_controller: AEServiciosBundle:GanarServicio:getTablaGanarFecha}
  