parameters:
#    ae_servicios.example.class: AE\ServiciosBundle\Example

services:
#    ae_servicios.example:
#        class: %ae_servicios.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
