ae_ganar_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AEGanarBundle:Default:index }
    
ganar_persona:
  pattern: /nuevo
  defaults: {_controller: AEGanarBundle:Registrar:persona}
  
ganar_addpersona:
  pattern: /regnuevo
  defaults: {_controller: AEGanarBundle:Registrar:addpersona}
  requirements:
    _method: POST
    
ganar_busqueda:
  pattern: /ganarbusqueda
  defaults: {_controller: AEGanarBundle:Busqueda:busqueda}
  
  
ganar_actualizarmiembro:
  pattern: /ganaractualizarmiembro
  defaults: {_controller: AEGanarBundle:Modificar:actualizarmiembro}
  requirements:
    _method: POST

ganar_vistamiembro:
  pattern: /ganarvista/{id}
  defaults: {_controller: AEGanarBundle:Busqueda:vista}
    
ganar_modificar:
  pattern: /ganarmodificar/{id}
  defaults: {_controller: AEGanarBundle:Modificar:modificar}
  
ganar_modificar_actualizar:
  pattern: /ganarmodificaractualizar
  defaults: {_controller: AEGanarBundle:Modificar:modificaractualizar}
  requirements:
    _method: POST
  
ganar_asignar_red:
  pattern: /ganarasignar
  defaults: {_controller: AEGanarBundle:Default:asignar}
  
ganar_asignar_red_actualizar:
  pattern: /ganarasignarupdate/
  defaults: {_controller: AEGanarBundle:Default:asignarupdate}
  requirements:
    _method: POST

ganar_eliminar_miembro:
  pattern: /eliminarmiembro/{id}
  defaults: {_controller: AEGanarBundle:Modificar:eliminarmiembro}
  
ganar_informe_ganar_fechas:
  pattern: /informe_ganar_fechas
  defaults: {_controller: AEGanarBundle:Informe:InformeGanarFechas}
  
ganar_informe_semanal:
  pattern: /informe_semanal
  defaults: {_controller: AEGanarBundle:Informe:InformeSemanal}