parameters:
#    ae_ganar.example.class: AE\GanarBundle\Example

services:
#    ae_ganar.example:
#        class: %ae_ganar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
