parameters:
  database_driver: pdo_pgsql
  database_host: 127.0.0.1
  database_port: 5432
  database_name: AE_DB_alfa
  database_user: postgres
  database_password: 'cs*marx*26041989'
  mailer_transport: gmail
  mailer_encryption: ssl
  mailer_auth_mode: login
  mailer_host: smtp.gmail.com
  mailer_user: artmar89
  mailer_password: 
  locale: en
  secret: ac9bd8548969f5321bae93b6dd13043ba0e475a7
  database_path: null