parameters:
  database_driver: pdo_pgsql
  database_host: actumbes.cmx8bf9qpm5t.us-east-1.rds.amazonaws.com
  database_port: 5432
  database_name: AC
  database_user: actumbes
  database_password: 'lQO8r4VH36Xz58Z'
  mailer_transport: gmail
  mailer_encryption: ssl
  mailer_auth_mode: login
  mailer_host: smtp.gmail.com
  mailer_user: artmar89
  mailer_password: 
  locale: en
  secret: ac9bd8548969f5321bae93b6dd13043ba0e475a7
  database_path: null
