parameters:
  database_driver: pdo_pgsql
  database_host: 127.0.0.1
  database_port: 5433
  database_name: AE_DB_T_v3
  database_user: postgres
  database_password: '260489'
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: ac9bd8548969f5321bae93b6dd13043ba0e475a7
  database_path: null
