parameters:
#    ae_discipular.example.class: AE\DiscipularBundle\Example

services:
#    ae_discipular.example:
#        class: %ae_discipular.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
