parameters:
#    ae_consolidar.example.class: AE\ConsolidarBundle\Example

services:
#    ae_consolidar.example:
#        class: %ae_consolidar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
