enviar_celula:
  pattern: /celula
  defaults: {_controller: AEEnviarBundle:Default:celula}
  
enviar_addcelula:
  pattern: /regcelula
  defaults: {_controller: AEEnviarBundle:Default:addcelula}
  requirements:
    _method: POST

enviar_temacelula:
  pattern: /temacelula
  defaults: {_controller: AEEnviarBundle:Default:temacelula}
  
enviar_temacelula_updated:
  pattern: /temacelula_updated
  defaults: {_controller: AEEnviarBundle:Default:temacelula_updated}
  requirements:
    _method: POST
    
enviar_crear_class_cell:
  pattern: /crear_class_cell
  defaults: {_controller: AEEnviarBundle:Default:crear_class_cell}
  
enviar_asistencia_celula:
  pattern: /asistencia_celula
  defaults: {_controller: AEEnviarBundle:Default:asistencia_celula}
  
enviar_lista_clases:
  pattern: /lista_clases
  defaults: {_controller: AEEnviarBundle:Default:lista_clases}