enviar_celula:
  pattern: /celula
  defaults: {_controller: AEEnviarBundle:Default:celula}
  
enviar_addcelula:
  pattern: /regcelula
  defaults: {_controller: AEEnviarBundle:Default:addcelula}
  requirements:
    _method: POST

enviar_temacelula:
  pattern: /temacelula
  defaults: {_controller: AEEnviarBundle:Default:temacelula}
  
enviar_temacelula_updated:
  pattern: /temacelula_updated
  defaults: {_controller: AEEnviarBundle:Default:temacelula_updated}
  requirements:
    _method: POST