enviar_celula:
  pattern: /celula
  defaults: {_controller: AEEnviarBundle:Default:celula}
  
enviar_addcelula:
  pattern: /regcelula
  defaults: {_controller: AEEnviarBundle:Default:addcelula}
  requirements:
    _method: POST

enviar_temacelula:
  pattern: /temacelula
  defaults: {_controller: AEEnviarBundle:Default:temacelula}
  
enviar_temacelula_updated:
  pattern: /temacelula_updated
  defaults: {_controller: AEEnviarBundle:Default:temacelula_updated}
  requirements:
    _method: POST

enviar_lista_clases:
  pattern: /lista_clases
  defaults: {_controller: AEEnviarBundle:Default:lista_clases}
  
enviar_lista_clases_descarga:
  pattern: /lista_clases_descarga
  defaults: {_controller: AEEnviarBundle:Default:lista_clases_descarga}
  requirements:
    _method: POST
    
enviar_crear_class_cell:
  pattern: /crear_class_cell
  defaults: {_controller: AEEnviarBundle:Default:crear_class_cell}

enviar_crear_class_cell_update:
  pattern: /crear_class_cell_update
  defaults: {_controller: AEEnviarBundle:Default:crear_class_cell_update}
  requirements:
    _method: POST
  
enviar_asistencia_celula:
  pattern: /asistencia_celula/{id}/{clase}
  defaults: {_controller: AEEnviarBundle:Default:asistencia_celula}
  
enviar_asistencia_celula_update:
  pattern: /asistencia_celula_update
  defaults: {_controller: AEEnviarBundle:Default:asistencia_celula_update}
  requirements:
    _method: POST
    
enviar_asistencia:
  pattern: /asistencia
  defaults: {_controller: AEEnviarBundle:Default:asistencia}

enviar_redes:
  pattern: /redes
  defaults: {_controller: AEEnviarBundle:Default:red}  
  
enviar_celulas_por_red:
  pattern: /celulas_por_red
  defaults: {_controller: AEEnviarBundle:Default:celulasbyred}  
  
  