parameters:
#    ae_enviar.example.class: AE\EnviarBundle\Example

services:
#    ae_enviar.example:
#        class: %ae_enviar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
