parameters:
#    clm_data.example.class: CLM\DataBundle\Example

services:
#    clm_data.example:
#        class: %clm_data.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
